### PR TITLE
Bump PSL and help with Debian packaging

### PR DESCRIPTION
**Pull request by pombredanne**
This is pretty small: the key changes are some fixes in packaging and a new PSL data list.
@kitterma FYI 
@KnitCode  you approval is welcomed!

### CODE REVIEW

**Comment by pombredanne** [comment]
@hiratara this also includes your latest pushes :bowing_man:

**Comment by pombredanne** [comment]
@dvzrv this would be the first release that I would start tagging as `release-2.release-2.20200127` as per #12

**Review by KnitCode — APPROVED** [review]
looks unicode... some of these public suffixes are amazingly complicated.  
hopefully the documentation is clear that folks need to use a flag to separate unicode for punyencoded cases. now at least they have the tests. :)

**Comment by pombredanne** [comment]
@KnitCode thank you. BTW do you write write access to this repo? You deserve it ++

**Pull request merged**
